### ISSUE TITLE
Incorrect health check result

### ISSUE THREAD

**Issue by sphiecoh** [lynxx131/dotnet.microservice#4]
I am testing the PostgresCheck and I stopped the `postgres` service but still I am getting healthy result which should not be the case.

I have confirmed via psql that postgres is not running :
```
 psql.exe -U postgres
psql: could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
```

The responses are not being cached, checked via chrome there is no `204` always `200`.

**Comment by sphiecoh** [comment]
This is the [fix](https://github.com/lynxx131/dotnet.microservice/pull/5).

**Comment by lynxx131** [comment]
Pushed to Nuget as version  1.1.4
